CREATE TABLE PERSONNE (
    idP INTEGER PRIMARY KEY ,
    nomP VARCHAR(15),
    prenomP VARCHAR(15)
);

CREATE TABLE DATE (
    idD INTEGER PRIMARY KEY,
    jour DATE NOT NULL,
);

CREATE TABLE REALISE (
    idP INTEGER NOT NULL,
    idD INTEGER NOT NULL,
    score INTEGER NOT NULL,
    PRIMARY KEY (idP, idD),
    FOREIGN KEY (idP) REFERENCES PERSONNE (idP) ON DELETE CASCADE,
    FOREIGN KEY (idD) REFERENCES DATE (idD) ON DELETE CASCADE
);
